### ISSUE TITLE
which one is the pearson modals component.

### ISSUE THREAD

**Issue by itjayaprakash** [Pearson-Higher-Ed/modal#33]
which one is the pearson modals  component.

This is the  download kit as per the design sample
https://uxframework.pearson.com/c/modal
 
But code 
1. https://www.npmjs.com/package/@pearson-ux/modal

or

2. https://www.npmjs.com/package/@pearson-components/modal

**Comment by antelopeb** [comment]
We are moving teams over to the new a11y modal:
